Added precision to bounding box with custom round function
wanadev/gltf-bounding-box pull request #6
Opened 2018-08-08 10:37 UTC by Giorat

Added precision to bounding box with custom round function.

This enables to get accurate sizes for objects.

Current users won't notice the change cause with default param the module API will act the same.

2018-08-09 09:17 UTC, risq commented
Thank you for your PR !!

Could you please add a few unit tests to test the precision option with the example model ?

Thanks.

2018-08-09 09:25 UTC, risq requested changes
By the way you don't need to include the dist files into the PR. They will be built in the following release !

2018-08-09 09:25 UTC, risq commented on src/glb2-bounding-box.js
> +  computeBoundings(glb,precision=0) {
Could you use a "parameters" object ? We may add more options in the future.

Something like

```js
  computeBoundings(glb, { precision = 0 } = {}) {
```

2018-08-09 09:25 UTC, risq commented on src/gltf1-bounding-box.js
> +  computeBoundings(gltf,precision=0) {
Same here.

2018-08-09 10:11 UTC, Giorat commented
I added dist build cause I wanted to use them as soon as possible on my projects. About tests, I tried fixing them but it kept failing with NaN results. Could it be caused by spy?

2018-08-09 13:41 UTC, risq commented
Indeed, I have investigated a little and I found out that the main function was passing a buffer object to gltf1 & glb functions as a second parameter, which was used as used as the precision in the `computeBoundings` methods.

I just pushed a fix on master, tell me if you still have issues with your tests.

2018-08-09 13:55 UTC, Giorat commented
Your commit is still failing the build: "The Travis CI build failed"

2018-08-09 15:10 UTC, risq commented
OK, it is fixed now, it was an issue between travis and some of the dependencies of gulp.

2018-10-11 08:40 UTC, Giorat commented
Can you merge this pull request? It might be really usefuel to have the variable precision for 3d models

2019-02-22 16:19 UTC, LambdaFalcon commented
Will this PR be merged? I'm not sure what the issue is with the failing build, but I agree with @Giorat that a precision parameter would be really helpful.

2019-02-28 08:38 UTC, LambdaFalcon commented
I forked the fork and corrected some issues, should I create a pull request with (my changes) to this repo or to @Giorat's fork?

2019-02-28 10:00 UTC, Giorat commented
To mine so then I can merge into this one! 😄

2019-03-01 15:33 UTC, LambdaFalcon commented
@Giorat done

2019-03-01 15:54 UTC, Giorat commented
> @Giorat done

Still present the issue

2019-03-01 16:01 UTC, LambdaFalcon commented
> Still present the issue

Yes, there are still merge conflicts, but we cannot do anything about those.
But the tests are now all passing

@risq what are the conflicts in `index.js` about?

2019-03-02 01:54 UTC, LambdaFalcon commented
@risq the build fails likely because of a problem with `gulp` and `node 11`: https://github.com/gulpjs/gulp/issues/2246

2019-03-19 16:38 UTC, merged